version: '3.8'

services:
  # PHP-FPM
  backend-php-fpm:
    # image: php:8.2-fpm
    container_name: nazir-testtask-php
    build:
      context: .
      dockerfile: ci-cd/php/Dockerfile
    # command: >
    #   sh -c "composer install"
    ports:
      - '9001:9000'
    env_file:
     - ./ci-cd/main.env
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      # XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      # PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - nazir-testtask-network
    depends_on:
      - database
    working_dir: /var/www/testtask
    volumes:
      - ./:/var/www/testtask
      - ./ci-cd/php/php.ini:/usr/local/etc/php/php.ini:ro

  # Web server - Nginx
  webserver-backend:
    image: nginx:latest
    container_name: "nazir-testtask-nginx"
    env_file:
     - ./ci-cd/main.env
    depends_on:
      - backend-php-fpm
    ports:
      - ${NGINX_HTTP_PORT}:80
    volumes:
      - ./:/var/www/testtask
      - ./ci-cd/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nazir-testtask-network

  # DBMS - PostgreSQL
  database:
    image: postgres:latest
    restart: always
    container_name: "nazir-testtask-db"
    env_file:
     - ./ci-cd/main.env
    environment:
      # POSTGRES_DB: testtask
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGPORT: 5432
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRES_PORT}:5432
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - nazir-testtask-network

# Docker Networks
networks:
  nazir-testtask-network:
    external: true
    # name: nazir-testtask-network
    # driver: bridge
    # ipam:
    #   config:
    #     - subnet: ${SUBNET_IP}
    #       gateway: ${SUBNET_MASK}
